### ISSUE TITLE
flac能正常播放，但是mp3不能

### ISSUE THREAD

**Issue by luoyanghero** [zanjie1999/httpRandomMusic#14]
flac能正常播放，但是mp3,updateFileList最后报如下错误。ffmpeg路径设置了，但这还没到ffmpeg那一步吧。
```
[~] # /share/CACHEDEV1_DATA/.qpkg/Apache83/bin/python3.11 /share/homes/admin/tool/httpRandomMusic.py
Server:         127.0.1.1
Address:        127.0.1.1#53

Name:   zyym.ie
Address: 192.168.0.7

12 files
11. 李希海 - 唐郊祀歌.flac
[~] # /share/CACHEDEV1_DATA/.qpkg/Apache83/bin/python3.11 /share/homes/admin/tool/httpRandomMusic.py
Server:         127.0.1.1
Address:        127.0.1.1#53

Name:   zyym.ie
Address: 192.168.0.7

1 files
Traceback (most recent call last):
  File "/share/homes/admin/tool/httpRandomMusic.py", line 139, in <module>
    updateFileList()
  File "/share/homes/admin/tool/httpRandomMusic.py", line 51, in updateFileList
    print(fileList[1])
          ~~~~~~~~^^^
IndexError: list index out of range
```
```
def updateFileList(search=''):
    global fileList
    global fileIndex
    try:
        os.chdir(fileDir)
    except Exception as e:
        print(e)
        print('ERROR: 请检查目录是否存在或是否有权限访问')
        exit()
    fileIndex = 0
    # fileList = list(filter(lambda x: x.lower().split('.')[-1] in ['flac','mp3','wav','aac','m4a'], os.listdir('.')))
    fileList = []
    for path, _, files in os.walk('.'):
        for f in files:
            if f.lower().split('.')[-1] in ['flac','mp3','wav','aac','m4a']:
                fpath = os.path.join(path, f)[2:]
                # 搜索关键词可以是文件夹名也可以是文件名
                if not search or search in fpath:
                    fileList.append(fpath)
    fileList.sort(key=lambda x: os.path.getmtime(x))
    fileList.reverse()
    print(str(len(fileList)) + ' files')
    print(fileList[1])
```

**Comment by zanjie1999** [comment]
那行是多余的，出错是因为你配置的目录中少于2个媒体文件

**Comment by luoyanghero** [comment]
好吧，现在是做测试，只放了一个文件-_-
